### ISSUE TITLE
Will/does this support include/filter/pagination

### ISSUE THREAD

**Issue by chrisjowen** [AgilionApps/ja_resource#21]
Hey Guys, 

This project looks very interesting, and I see its early days but I wonder are you planning to support the json-api spec for including associations, filtering etc? I tried ```/model/?include=otherModel``` but no joy, looking around the code it doesn't seem to be implement yet just wondering if it will be there in the future?

Same with pagination etc

Chris

**Comment by alanpeabody** [comment]
Hi Chris,

Pagination is not supported yet, but I was thinking of adding support via a handle query hook: https://github.com/AgilionApps/ja_resource/issues/5

Filtering is currently supported, however I am not totally satisfied with the API and it will be changing to at least include the conn in the arguments. I have not documented it yet since it is likely to change, but is it basically adding `def filter("user", query, username), do: #return query`. It expects filters to come in as: `/issues/?filter[user]=chrisjowen`
https://github.com/AgilionApps/ja_resource/blob/master/lib/ja_resource/index.ex#L49

Includes should be passed through to the serializer as options:
https://github.com/AgilionApps/ja_resource/blob/master/lib/ja_resource/serializable.ex#L2
https://github.com/AgilionApps/ja_serializer#include

If you run into issues with that please ping me again on this ticket.

**Comment by chrisjowen** [comment]
Hey, 

Thanks for that, I added include as described to the serializer but it complains that I need to prefetch the assosiation: ```The venues relationship returned %Ecto.Association.NotLoaded{}.``` I may be mistaken but I thought that by adding include the ja_resource lib would add the prefetch

**Comment by alanpeabody** [comment]
I didn't feel it was a great idea to have the library automatically include things without the developers explicit doing so, however maybe this is a hook that should be added similar to filter?

For now I would handle the logic in handle_index:

```elixir
def handle_index(conn, %{"include" => include}) do
  includes = String.split(include, ",")
  query = records(conn)
  query = if "venues" in includes, do: Ecto.Query.preload(query, [:venues]), else: query
  query
end
```
(that could be better code)

**Comment by chrisjowen** [comment]
Thanks for the response, I came to the same conclusion about using handle_index though it seems to defeat the point for me. What I don't understand is without prefetching how would include ever be useful?

**Comment by chrisjowen** [comment]
Incidentally does your suggestion work for you, I have now a very strange error at https://github.com/AgilionApps/ja_serializer/blob/master/lib/ja_serializer/builder/top_level.ex#L24

```no function clause matching in Keyword.put/3```

This seems very odd to me as Keyword clearly does have a function Keyword.put/3 so I am baffled.

**Comment by alanpeabody** [comment]
Honestly it just isn't something I have dug into heavily quite yet in this library (or frankly actually used in production - I haven't worked with any clients that support the include param).

I am very open to contributions and suggestions to improve all parts of this library.

However my general feeling is that I don't want to just arbitrarily trust user input from the end user, much like filtering is a "ignored unless defined" pattern. At the very least a whitelist and defaults that can be overriden. 

I have not experienced that error, I can take a look in the next few days, but I would guess somehow opts is a map instead of a keyword list or something.

**Comment by chrisjowen** [comment]
Ok thats interesting,I am extremely new to the json-api and I have similar concerns to you regarding giving such power to the user input. Being so new to this, I am open to thoughts on best practices and I  am interested in in what you said about not ever using include. 

Am I right in assuming that you did actually still represent associated relationships in your resources, but you explicitly do this and not via the query parameter? 

There does still feel like a disconnect if this isn't done though, as I can define a has_one/has_many relationship in the serializers and using ja_resource as is (without messing with handle_x callbacks) I cannot render these relationships. 

I think I would feel it would be nice to use this, for ease of development, and become more explicit and disable this when I find the 'shape' of my api and before I push to production. I certainly feel that out-of-the-box this would be nice functionality, but a whitelist or ability to toggle it does seem like a must. 

I guess with the handle_x callbacks, it wouldn't be too difficult to write a few macros that I could conditionally require/use to prefetch while in early dev. 

I wonder, would it be possible to use the serializers definitions to determine a whitelist. In other words if there is a has_one/has_many relationship defined then they can be included via the query string params (and would be prefetched if specified) any other relationships not defined in the serializer could be ignored or raise an error.

Anyway these are just rambling thoughts, I think this is great work and appreciate the OSS contributions.

**Comment by alanpeabody** [comment]
I hadn't thought about checking the view.... Something to look into for sure.
